config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :currencies, only: [:index] do
    get 'convert', on: :collection
    get 'historical_chart', on: :collection
  end

  root "currencies#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/currency.rb
class Currency < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/currencies_controller.rb
class CurrenciesController < ApplicationController
  def index
    @currencies = Currency.all
  end

  def convert
    api_key = ENV['CURRENCY_API'] 
    converter = CurrencyConverter.new(api_key)

    return if params[:amount].blank?

    @base_currency = params[:base_currency]
    @target_currency = params[:target_currency]
    @amount = params[:amount].to_f

    @converted_amount = converter.live_exchange_rate(@base_currency, @target_currency) * @amount
    respond_to do |format|
      format.html { render 'index' } # Add this line if you still want to handle HTML requests
      format.json { render json: { converted_amount: @converted_amount } }
    end
  end

  def historical_chart
    api_key = ENV['CURRENCY_API']
    converter = CurrencyConverter.new(api_key)

    base_currency = params[:base_currency]
    target_currency = params[:target_currency]
    start_date = params[:start_date]
    end_date = params[:end_date]

    historical_rates = converter.historical_exchange_rate(base_currency, target_currency, start_date, end_date)
    historical_array = historical_rates.map do |date, data|
	  [date, data["#{base_currency}#{target_currency}"]]
	end
	@sorted_historical_array = historical_array.sort_by { |date, _| date }

    puts "API Response: #{@historical_rates.inspect}"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/currencies_helper.rb
module CurrenciesHelper
end

app/views/currencies/historical_chart.html.erb
<h1>Historical Exchange Rate Chart</h1>

<%= form_tag(historical_chart_currencies_path, method: :get) do %>
  <%= label_tag 'Base Currency' %>
  <%= select_tag :base_currency, options_for_select(Currency.pluck(:code)) %>

  <%= label_tag 'Target Currency' %>
  <%= select_tag :target_currency, options_for_select(Currency.pluck(:code)) %>

  <%= label_tag 'Start Date' %>
  <%= text_field_tag :start_date, Date.today - 30.days %>

  <%= label_tag 'End Date' %>
  <%= text_field_tag :end_date, Date.today %>

  <%= submit_tag 'Show Chart' %>
<% end %>

<% if @sorted_historical_array %>
  <%= line_chart @sorted_historical_array, library: { title: { text: 'Historical Exchange Rates' } } %>
  <%= line_chart [[2,3],[4,5]], library: { title: { text: 'Historical Exchange Rates' } } %>
<% end %>

app/views/currencies/index.html.erb
<h1>Currencies Converter</h1>

<%= form_tag(convert_currencies_path, method: :get) do %>
  <%= label_tag 'Base Currency' %>
  <%= select_tag :base_currency, options_for_select(Currency.pluck(:code)) %>

  <%= label_tag 'Target Currency' %>
  <%= select_tag :target_currency, options_for_select(Currency.pluck(:code)) %>

  <%= label_tag 'Amount' %>
  <%= text_field_tag :amount %>

  <%= submit_tag 'Convert' %>
<% end %>

<% if @converted_amount %>
  <p>Converted Amount: <%= "#{@amount} #{@base_currency} = #{@converted_amount} #{@target_currency}" %></p>
<% end %>

<%= link_to 'Historical Chart', historical_chart_currencies_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CurrencyConverter</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>